pretrain: 
resume:
seed: 1024
data:
    root: 'enter your data root'
    dataset: hmdb51
    modality: RGB
    num_segments: 8
    seg_length: 1
    split: 1
    batch_size: 32
    workers: 1
    gpus: 2
    num_classes: 51
    image_tmpl: 'img_{:05d}.jpg'
    train_list: 'lists/hmdb51/train_rgb_5shot_split1.txt' #
    val_list: 'lists/hmdb51/val_rgb_split1.txt' #
    label_list: 'lists/hmdb51_labels.csv'
    index_bias: 1
    input_size: 224
    randaug:
        N: 0 #2
        M: 0  #9
network:
    arch: ViT-B/16  #ViT-B/32 ViT-B/16
    init: True 
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_hmdb
    sim_header: "Transf"  #Transf   meanP   LSTM   Transf_cls Conv_1D
    fix_text: False
    fix_img: False
    describe:
solver:
    type: cosine
    epochs: 40
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 0.001
    lr_warmup_step: 4
    momentum: 0.9
    weight_decay: 0.01
    lr_decay_step: 15
    lr_decay_factor: 0.1
    clip_gradient: 5
    loss_type: nll
    evaluate: False
    ratio: 1
    f_ratio: 10
    use_text_adapter: True
    text_adapter_layers: [11]
    text_adapter_dim: 128
    use_visual_adapter: True
    visual_adapter_layers: [10,11]
    visual_adapter_dim: 128
logging:
    print_freq: 10
    eval_freq: 1